name: snowflake-multistages

# Controls when the action will run.
on:
  push:
    branches:
      - main
    paths:
      - 'migrations/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  Dev:
    runs-on: ubuntu-latest
    environment: DEV

    steps:
      # Checks out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Use Python 3.8.x
        uses: actions/setup-python@v2.2.1
        with:
          python-version: 3.8.x

      - name: Run schemachange
        env:
          SF_ACCOUNT: ${{ secrets.SF_DEV_ACCOUNT }}
          SF_USERNAME: ${{ secrets.SF_DEV_USERNAME }}
          SF_ROLE: ${{ secrets.SF_DEV_ROLE }}
          SF_WAREHOUSE: ${{ secrets.SF_DEV_WAREHOUSE }}
          SF_DATABASE: ${{ secrets.SF_DEV_DATABASE}}  # Use environment specific database
          SNOWFLAKE_PASSWORD: ${{ secrets.SF_DEV_PASSWORD }}
        run: |
          echo "GITHUB_WORKSPACE: $GITHUB_WORKSPACE"
          python --version
          echo "Step 1: Installing schemachange"
          pip install schemachange
          echo "Step 2: Running schemachange"
          schemachange -f $GITHUB_WORKSPACE/migrations -a $SF_ACCOUNT -u $SF_USERNAME -r $SF_ROLE -w $SF_WAREHOUSE -d $SF_DATABASE -c $SF_DATABASE.SCHEMACHANGE.CHANGE_HISTORY --create-change-history-table
      
          
  UAT:
    runs-on: ubuntu-latest
    environment: UAT
    needs: Dev

    steps:
      # Checks out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Use Python 3.8.x
        uses: actions/setup-python@v2.2.1
        with:
          python-version: 3.8.x
          
      - name: Run schemachange
        env:
          SF_ACCOUNT: ${{ secrets.SF_UAT_ACCOUNT }}
          SF_USERNAME: ${{ secrets.SF_UAT_USERNAME }}
          SF_ROLE: ${{ secrets.SF_UAT_ROLE }}
          SF_WAREHOUSE: ${{ secrets.SF_UAT_WAREHOUSE }}
          SF_DATABASE: ${{ secrets.SF_UAT_DATABASE}}  # Use environment specific database
          SNOWFLAKE_PASSWORD: ${{ secrets.SF_UAT_PASSWORD }}
        run: |
          echo "GITHUB_WORKSPACE: $GITHUB_WORKSPACE"
          python --version
          echo "Step 1: Installing schemachange"
          pip install schemachange
          echo "Step 2: Running schemachange"
          schemachange -f $GITHUB_WORKSPACE/migrations -a $SF_ACCOUNT -u $SF_USERNAME -r $SF_ROLE -w $SF_WAREHOUSE -d $SF_DATABASE -c $SF_DATABASE.SCHEMACHANGE.CHANGE_HISTORY --create-change-history-table
        
  PROD:
      runs-on: ubuntu-latest
      environment: PROD
      needs: UAT

      steps:
      # Checks out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Use Python 3.8.x
        uses: actions/setup-python@v2.2.1
        with:
          python-version: 3.8.x
          
      - name: Run schemachange
        env:
          SF_ACCOUNT: ${{ secrets.SF_PROD_ACCOUNT }}
          SF_USERNAME: ${{ secrets.SF_PROD_USERNAME }}
          SF_ROLE: ${{ secrets.SF_PROD_ROLE }}
          SF_WAREHOUSE: ${{ secrets.SF_PROD_WAREHOUSE }}
          SF_DATABASE: ${{ secrets.SF_PROD_DATABASE}}  # Use environment specific database
          SNOWFLAKE_PASSWORD: ${{ secrets.SF_PROD_PASSWORD }}
        run: |
          echo "GITHUB_WORKSPACE: $GITHUB_WORKSPACE"
          python --version
          echo "Step 1: Installing schemachange"
          pip install schemachange
          echo "Step 2: Running schemachange"
          schemachange -f $GITHUB_WORKSPACE/migrations -a $SF_ACCOUNT -u $SF_USERNAME -r $SF_ROLE -w $SF_WAREHOUSE -d $SF_DATABASE -c $SF_DATABASE.SCHEMACHANGE.CHANGE_HISTORY --create-change-history-table
